### PR TITLE
FIX issue #428 for high density touchpad

### PR DESCRIPTION
**Pull request by mbarbierato**
Fix issue #428 for high density touchpad 
issue opened by @Lorys89 on VoodooI2C project

### CODE REVIEW

**Comment by Lorys89** [comment]
> Fix issue #428 for high density touchpad
> issue opened by @Lorys89 on VoodooI2C project

thanks @mbarbierato  :) i2c work good now

**Comment by dreamwhite** [comment]
Where does 2.54 value come from? May you provide some documentation? :')

**Comment by Vorshim92** [comment]
thanks a lot @mbarbierato! your version works perfectly and smoothly on my HP x360 Pavilion ICELAKE with trackpad brand ELAN <3 <3 <3 <3

**Comment by Vorshim92** [comment]
thanks a lot @mbarbierato! your version works perfectly and smoothly on my HP x360 Pavilion ICELAKE with trackpad brand ELAN <3 <3 <3 <3

**Comment by Lorys89** [comment]
> thanks a lot @mbarbierato! your version works perfectly and smoothly on my HP x360 Pavilion ICELAKE with trackpad brand ELAN <3 <3 <3 <3

it's a great result, and even more so that it also solves on your laptop 💪
Kind regards

**Comment by ben9923** [comment]
@mbarbierato Thanks for the PR!

I couldn't understand why it works, and definitely can't be sure it won't break any other device.
Please elaborate.

@dreamwhite 1 inch = 2.54 centimeters. Not sure why this value is used...

**Comment by dreamwhite** [comment]
> @mbarbierato Thanks for the PR!
> 
> I couldn't understand why it works, and definitely can't be sure it won't break any other device.
> Please elaborate. A reference to matching Linux handling of such cases would be great.
> 
> @dreamwhite 1 inch = 2.54 centimeters. Not sure why this value is used...

:'( me neither. Probably 2.54 value comes from 1 inch2cm conversion but probably the author of the PR will provide the necessary documentation

**Comment by Goshin** [comment]
https://github.com/VoodooI2C/VoodooI2CHID/blob/e8e2f90b2f233147b90491e6bfaaec29a10bb518/VoodooI2CHID/VoodooI2CMultitouchHIDEventDriver.cpp#L530-L536

The unit is determined by the byte given by `sub_element->getUnit()`.

It might have something to do with the unit obtaining? because I don't see the relation between `logical_max_x` and `physical_max_x`.

**Comment by mbarbierato** [comment]
> The unit is determined by the byte given by `sub_element->getUnit()`.
> 
> It might have something to do with the unit obtaining? because I don't see the relation between `logical_max_x` and `physical_max_x`.

Hi @Goshin the unit value is 0x11 here all the value reported by the original kext:
[    2.765020]: VoodooI2CPrecisionTouchpadHIDEventDriver::DELL09EA logical_max_x : 3438 
[    2.765023]: VoodooI2CPrecisionTouchpadHIDEventDriver::DELL09EA raw_physical_max_x : 11440 
[    2.765025]: VoodooI2CPrecisionTouchpadHIDEventDriver::DELL09EA raw_unit_exponent : 13 
[    2.765026]: VoodooI2CPrecisionTouchpadHIDEventDriver::DELL09EA unit : 17 
[    2.765027]: VoodooI2CPrecisionTouchpadHIDEventDriver::DELL09EA physical_max_x : 11440 
[    2.765029]: VoodooI2CPrecisionTouchpadHIDEventDriver::DELL09EA logical_max_y : 2170 
[    2.765031]: VoodooI2CPrecisionTouchpadHIDEventDriver::DELL09EA raw_physical_max_y : 6940 
[    2.765032]: VoodooI2CPrecisionTouchpadHIDEventDriver::DELL09EA raw_unit_exponent : 13 
[    2.765033]: VoodooI2CPrecisionTouchpadHIDEventDriver::DELL09EA unit : 17 
[    2.765035]: VoodooI2CPrecisionTouchpadHIDEventDriver::DELL09EA physical_max_y : 6940

**Comment by mbarbierato** [comment]
> @mbarbierato Thanks for the PR!
> 
> 
> 
> I couldn't understand why it works, and definitely can't be sure it won't break any other device.
> 
> Please elaborate. A reference to matching Linux handling of such cases would be great.
> 
> 
> 
> @dreamwhite 1 inch = 2.54 centimeters. Not sure why this value is used...

Hi @ben9923 thanks for your work i closed this pr for study

**Pull request closed without merging**
