### PR TITLE
Publish "RM,deliverNotifications" in handleStart for possible race condition

### PR DESCRIPTION
**Pull request by zhen-zen**
https://github.com/VoodooI2C/VoodooI2C/issues/427
https://github.com/acidanthera/bugtracker/issues/1415

CC @witampanstwa @lvs1974 @ben9923

### CODE REVIEW

**Comment by ben9923** [comment]
From my understanding the issue is fixed with just https://github.com/acidanthera/VoodooPS2/commit/dc3571249f59d3aa0bfd867596bb7121373c8ee9, isn't it?

**Comment by lvs1974** [comment]
@ben9923: at least that fix solved issue for me and @witampanstwa, so I think it should work for everyone.

**Comment by witampanstwa** [comment]
> @ben9923: at least that fix solved issue for me and @witampanstwa, so I think it should work for everyone.

That is, if your configuration uses GPIO interrupts because mine does use pooling (unless you're sure that it does indeed work in the GPIO mode too)

**Comment by zhen-zen** [comment]
I think the workaround is weird for a race condition issue but @lvs1974 discovered that the `IONotify` pointer could differ. Later I dug into the IOKit source code [further](https://github.com/acidanthera/bugtracker/issues/1415#issuecomment-758343804) but it seems that the mechanism should work reliably. Since I don't have resources to test it right now, I will just close this PR.

**Pull request closed without merging**
